import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class Driver {

    /**
     * Driver class main method
     * @param args
     * @throws SQLException
     */
    public static void main(String[] args) {
        // MySql credentials
        String mySqlConnectionUrl = "jdbc:mysql://pgc-sd-bigdata.cyaielc9bmnf.us-east-1.rds.amazonaws.com:3306/pgcdata";
        String user = "student";
        String password = "STUDENT123";;

        // MongoDB Configurations
        String mongoDbConnectionUrl = "mongodb://localhost:27017";//"mongodb://ec2-3-230-166-172.compute-1.amazonaws.com:27017";

        // Connection Default Value Initialization
        Connection sqlConnection = null;
        MongoClient mongoClient = null;

        try {
            // Creating  sql database connections
            sqlConnection = DriverManager.getConnection(mySqlConnectionUrl, user, password);

            // Creating  mongo database connections
           mongoClient =  MongoClients.create(mongoDbConnectionUrl);
           MongoDatabase db = mongoClient.getDatabase("upgrad");
           MongoCollection<Document> collection = db.getCollection("products");


            // Import data into MongoDb
            CRUDHelper.importDataToMongoDB(sqlConnection,collection);

            // List all products in the inventory
            CRUDHelper.displayAllProducts(collection);

            // Display top 5 Mobiles
            CRUDHelper.displayTop5Mobiles(collection);

            // Display products ordered by their categories in Descending Order Without autogenerated Id
            CRUDHelper.displayCategoryOrderedProductsDescending(collection);

            // Display product count in each category
            CRUDHelper.displayProductCountByCategory(collection);

            // Display wired headphones
            CRUDHelper.displayWiredHeadphones(collection);
        }
        catch(SQLException ex) {
            System.out.println("Got  Sql Exception.");
            ex.printStackTrace();
        }
        finally {
            if(sqlConnection!=null) {
                try {
                    sqlConnection.close();
                } catch (SQLException e) {
                    System.out.println("Got Exception while closing SQL connection.");
                    e.printStackTrace();
                }
            }
            if(mongoClient!=null) {
                    mongoClient.close();
            }

        }
    }

}